services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloudnotes
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

  api:
    image: ghcr.io/vladmarianpitariu/cloudnotes:latest   # ← pull from GHCR
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/cloudnotes
    ports:
      - "8000:8000"

volumes:
  dbdata:
